from php:8.2-fpm

# Install required dependencies
RUN apt-get update && apt-get install -y \
    git \
    unzip

RUN php --version

# Set COMPOSER_ALLOW_SUPERUSER=1 to allow plugins to run as root
ENV COMPOSER_ALLOW_SUPERUSER=1 

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN echo "Composer version:" && composer --version

WORKDIR /var/www/html

# COPY composer.json /var/www/html

# RUN composer install --no-interaction --no-plugins --no-scripts

RUN addgroup --gid 3000 --system app \
    && adduser --uid 3000 --system --disabled-login --disabled-password --gid 3000 app \
    && docker-php-ext-install pdo_mysql mysqli \
    && set -ex; \
    	cd /usr/local/etc  \
    && { \
		echo '[global]'; \
		echo 'daemonize = no'; \
		echo; \
		echo '[www]'; \
		echo 'listen = /sock/docker.sock'; \
		echo 'listen.owner = app'; \
		echo 'listen.group = app'; \
		echo 'listen.mode = 0660'; \
	} | tee php-fpm.d/zz-docker.conf




